server:
  port: 9999
spring:
  application:
    name: demom
  sql:
    init:
      #schema-locations:
      #  - classpath:testdb/schema/schema.sql
      data-locations:
        - classpath:db/data/data.sql
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.HSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      #generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

#logging:
  #level:
    #org.hibernate.type: trace
    #org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql: trace